/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeekWeekIdRouteImport } from './routes/week.$weekId'
import { Route as DayDayIdRouteImport } from './routes/day.$dayId'

const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekWeekIdRoute = WeekWeekIdRouteImport.update({
  id: '/week/$weekId',
  path: '/week/$weekId',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDayIdRoute = DayDayIdRouteImport.update({
  id: '/day/$dayId',
  path: '/day/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/glossary': typeof GlossaryRoute
  '/library': typeof LibraryRoute
  '/day/$dayId': typeof DayDayIdRoute
  '/week/$weekId': typeof WeekWeekIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/glossary': typeof GlossaryRoute
  '/library': typeof LibraryRoute
  '/day/$dayId': typeof DayDayIdRoute
  '/week/$weekId': typeof WeekWeekIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/glossary': typeof GlossaryRoute
  '/library': typeof LibraryRoute
  '/day/$dayId': typeof DayDayIdRoute
  '/week/$weekId': typeof WeekWeekIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/glossary'
    | '/library'
    | '/day/$dayId'
    | '/week/$weekId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/glossary'
    | '/library'
    | '/day/$dayId'
    | '/week/$weekId'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/glossary'
    | '/library'
    | '/day/$dayId'
    | '/week/$weekId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRoute
  GlossaryRoute: typeof GlossaryRoute
  LibraryRoute: typeof LibraryRoute
  DayDayIdRoute: typeof DayDayIdRoute
  WeekWeekIdRoute: typeof WeekWeekIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week/$weekId': {
      id: '/week/$weekId'
      path: '/week/$weekId'
      fullPath: '/week/$weekId'
      preLoaderRoute: typeof WeekWeekIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$dayId': {
      id: '/day/$dayId'
      path: '/day/$dayId'
      fullPath: '/day/$dayId'
      preLoaderRoute: typeof DayDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRoute,
  GlossaryRoute: GlossaryRoute,
  LibraryRoute: LibraryRoute,
  DayDayIdRoute: DayDayIdRoute,
  WeekWeekIdRoute: WeekWeekIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
